# Generated by Django 6.0.5 on 2026-07-22 17:45

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_image'),
    ]

    operations = [
            TrigramExtension()
    ]
