# Generated by Django 6.0.5 on 2026-07-22 17:52

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'content'], name='post_title_content_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
